version: "3"
services:
  python-api:
    build:
      context: .
      dockerfile: ./.devcontainer/python-container/Dockerfile
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    links:
      - node-app

  node-app:
    build:
      context: .
      dockerfile: ./.devcontainer/node-container/Dockerfile
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
